# Generated by Django 5.1.6 on 2025-03-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deactivation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deactivation_requested',
        ),
    ]
